#!/bin/sh
#BSUB -J [NAME]
#BSUB -q [QUEUE]
#BSUB -n [LFSCORES]
#BSUB -R "span[hosts=[LFSHOSTS]]"
#BSUB -W [WALLCLOCK]
#BSUB -u null@dtu.dk
#BSUB -B
#BSUB -N
#BSUB -o Output_%J.out
#BSUB -e Error_%J.err

# Temporary fix on DTU HPC
.  /etc/profile.d/machinetype.sh

# load the necessary modules
module load gcc/4.8.4
module load mpi/gcc-openmpi-1.6.5-lsfib
module load amber/14-gcc-4.8.4

echo "CURRENT CPU TYPE"
echo $CPUTYPEV
echo "AMBER HOME DIRECTORY:"
echo $AMBERHOME